// <auto-generated />
using System;
using EasyPark.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EasyPark.Infrastructure.Migrations
{
    [DbContext(typeof(EasyParkContext))]
    partial class EasyParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyPark.Api.Models.Bairro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CidadeId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CIDADE_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("Nome", "CidadeId")
                        .IsUnique();

                    b.ToTable("BAIRRO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Cidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NOME");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("UF_SIGLA");

                    b.HasKey("Id");

                    b.HasIndex("UfSigla");

                    b.HasIndex("Nome", "UfSigla")
                        .IsUnique();

                    b.ToTable("CIDADE");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BairroId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BAIRRO_ID");

                    b.Property<string>("Cep")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Logradouro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Numero")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("ENDERECO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Estacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ENDERECO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<long>("OperadoraId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("OPERADORA_ID");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("ESTACIONAMENTO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Nivel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EstacionamentoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ESTACIONAMENTO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("NIVEL");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("GatewayProvider")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("GATEWAY_PROVIDER");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("GATEWAY_RESPONSE");

                    b.Property<string>("GatewayTxId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("GATEWAY_TX_ID");

                    b.Property<string>("IdempotenciaChave")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("IDEMPOTENCIA_CHAVE");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("METODO_PAGAMENTO");

                    b.Property<long?>("ReservaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RESERVA_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.ToTable("PAGAMENTO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.PagamentoCartao", b =>
                {
                    b.Property<long>("PagamentoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PAGAMENTO_ID");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("BANDEIRA");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("TITULAR_NOME");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TOKEN");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR2(4)")
                        .HasColumnName("FINAL_CARTAO");

                    b.HasKey("PagamentoId");

                    b.ToTable("PAGAMENTO_CARTAO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.PagamentoPagador", b =>
                {
                    b.Property<long>("PagamentoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PAGAMENTO_ID");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF_CNPJ");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<long?>("EnderecoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ENDERECO_ID");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("PagamentoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("PAGAMENTO_PAGADOR");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Reserva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AntecedenciaMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANTECEDENCIA_MINUTOS");

                    b.Property<DateTimeOffset?>("ConfirmadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CONFIRMADO_EM");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTimeOffset?>("DataInicio")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("INICIO_PREVISTO");

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACAO_MINUTOS");

                    b.Property<DateTimeOffset?>("EtaAtualizadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("ETA_ATUALIZADO_EM");

                    b.Property<int?>("EtaMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ETA_MINUTOS");

                    b.Property<string>("EtaOrigem")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ETA_ORIGEM");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("MOTIVO_CANCELAMENTO");

                    b.Property<DateTimeOffset?>("OcupadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("OCUPADO_EM");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("PAGO_EM");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ESTADO");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("VagaBloqueada")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("VAGA_BLOQUEADA");

                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.ToTable("RESERVA");
                });

            modelBuilder.Entity("EasyPark.Api.Models.ReservaHist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DataAlteracao")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("OCORRIDO_EM");

                    b.Property<string>("FromEstado")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("FROM_ESTADO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("OrigemEvento")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ORIGEM_EVENTO");

                    b.Property<long?>("ReferenciaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("REFERENCIA_ID");

                    b.Property<long>("ReservaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RESERVA_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TO_ESTADO");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("RESERVA_HIST");
                });

            modelBuilder.Entity("EasyPark.Api.Models.ReservaPreco", b =>
                {
                    b.Property<long>("ReservaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RESERVA_ID");

                    b.Property<int?>("AntecedenciaMinutosAplicada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANTECEDENCIA_MINUTOS_APLICADA");

                    b.Property<DateTimeOffset?>("CalculadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CALCULADO_EM");

                    b.Property<string>("Moeda")
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("MOEDA");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<decimal?>("PercentualAntecedencia")
                        .HasPrecision(8, 6)
                        .HasColumnType("DECIMAL(8,6)")
                        .HasColumnName("PERCENTUAL_ANTECEDENCIA");

                    b.Property<decimal?>("TarifaPorMinuto")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)")
                        .HasColumnName("TARIFA_POR_MINUTO");

                    b.Property<decimal?>("ValorFinal")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)")
                        .HasColumnName("VALOR_FINAL");

                    b.Property<decimal?>("ValorPrevisto")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)")
                        .HasColumnName("VALOR_PREVISTO");

                    b.HasKey("ReservaId");

                    b.ToTable("RESERVA_PRECO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTimeOffset?>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.ToTable("SENSOR");
                });

            modelBuilder.Entity("EasyPark.Api.Models.SensorEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("OCORRIDO_EM");

                    b.Property<string>("Payload")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PAYLOAD");

                    b.Property<DateTimeOffset?>("RecebidoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("RECEBIDO_EM");

                    b.Property<long>("SensorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SENSOR_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.ToTable("SENSOR_EVENTO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.TipoVaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EhAcessivel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("EH_ACESSIVEL");

                    b.Property<string>("EhEletrica")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("EH_ELETRICA");

                    b.Property<string>("EhMoto")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("EH_MOTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("TarifaPorMinuto")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)")
                        .HasColumnName("TARIFA_POR_MINUTO");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TIPO_VAGA");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Uf", b =>
                {
                    b.Property<string>("Sigla")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SIGLA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Sigla");

                    b.ToTable("UF");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("NoShows")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NO_SHOWS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("NOME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PERFIL");

                    b.Property<DateTimeOffset?>("SuspensaoAte")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("SUSPENSAO_ATE");

                    b.Property<string>("Suspenso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SUSPENSO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Vaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTimeOffset?>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CRIADO_EM");

                    b.Property<long>("NivelId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NIVEL_ID");

                    b.Property<long>("TipoVagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TIPO_VAGA_ID");

                    b.HasKey("Id");

                    b.HasIndex("NivelId", "Codigo")
                        .IsUnique();

                    b.ToTable("VAGA");
                });

            modelBuilder.Entity("EasyPark.Api.Models.VagaStatus", b =>
                {
                    b.Property<long>("VagaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VAGA_ID");

                    b.Property<long?>("SensorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SENSOR_ID");

                    b.Property<string>("StatusOcupacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_OCUPACAO");

                    b.Property<DateTimeOffset?>("UltimoOcorrido")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("ULTIMO_OCORRIDO");

                    b.HasKey("VagaId");

                    b.ToTable("VAGA_STATUS");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Bairro", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Cidade", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Uf", "Uf")
                        .WithMany()
                        .HasForeignKey("UfSigla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Endereco", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("EasyPark.Api.Models.Estacionamento", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("EasyPark.Api.Models.PagamentoCartao", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Pagamento", null)
                        .WithOne()
                        .HasForeignKey("EasyPark.Api.Models.PagamentoCartao", "PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPark.Api.Models.PagamentoPagador", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyPark.Api.Models.Pagamento", null)
                        .WithOne()
                        .HasForeignKey("EasyPark.Api.Models.PagamentoPagador", "PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("EasyPark.Api.Models.ReservaHist", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPark.Api.Models.ReservaPreco", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Reserva", null)
                        .WithOne()
                        .HasForeignKey("EasyPark.Api.Models.ReservaPreco", "ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyPark.Api.Models.VagaStatus", b =>
                {
                    b.HasOne("EasyPark.Api.Models.Vaga", null)
                        .WithOne()
                        .HasForeignKey("EasyPark.Api.Models.VagaStatus", "VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
