<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Data\EasyParkContext.cs" Link="Data\EasyParkContext.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**\*;bin\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyPark.Domain\EasyPark.Domain.csproj" />
    <ProjectReference Include="..\EasyPark.Application\EasyPark.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.21.121" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.120" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
  </ItemGroup>
</Project>
