<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Dtos\**\*.cs" Link="Dtos\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Services\**\*.cs" Link="Services\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Observability\EasyParkTelemetry.cs" Link="Observability\EasyParkTelemetry.cs" />
    <Compile Include="**\*.cs" Exclude="obj\**\*;bin\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyPark.Domain\EasyPark.Domain.csproj" />
  </ItemGroup>
</Project>
